[package]
name = "nerdnet"
version = "0.0.1"
edition = "2021"
authors = ["Ettore Delprino <edelprino@gmail.com>"]

[dependencies]
serde = {version = "1.0.195", features = ["derive"]}
serde_json = "1.0.80"
serde_yaml = "0.9.30"
ureq = {version = "2.9", features = ["json"]}
